name: speed_analysis
description: Test task.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.17.0
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  mocktail: ^0.3.0
  test: ^1.22.0

flutter:
  uses-material-design: true
