name: speed_analysis
description: Test task.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  collection: 1.17.0
  csv: 5.0.2
  cupertino_icons: 1.0.5
  file_picker: 5.3.0
  flutter_bloc: 8.1.3
  freezed_annotation: 2.4.1
  get_it: 7.6.0
  injectable: 2.1.2
  syncfusion_flutter_charts: 21.1.41

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.3.0
  flutter_lints: 2.0.2
  freezed: 2.4.1
  injectable_generator: 2.1.6
  mocktail: 0.3.0
  test: 1.22.0

flutter:
  uses-material-design: true
